version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Backend
    container_name: backend
    secrets:
      - secret-backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: frontend
    environment:
      - VITE_API_URL=/api/
    ports:
      - "5173:3001"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data:

networks:
  app-network:

secrets:
  secret-backend:
    file: ./secret-backend.txt